"""create_users_table

Revision ID: ffdc0a98111c
Revises:
Create Date: 2020-11-20 15:06:02.230689

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('likes', sa.Integer()),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'])
    )

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('likes', sa.Integer()),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'])
    )

    op.create_table('merchandise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'])
    )

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.Column('record', sa.String(), nullable=False),
    sa.Column('playoffs', sa.String(), nullable=False),
    sa.Column('coach', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('number', sa.Integer),
    sa.Column('goals', sa.Integer()),
    sa.Column('assists', sa.Integer()),
    sa.Column('points', sa.Integer()),
    sa.Column('pims', sa.Integer()),
    sa.Column('plus_minus', sa.Integer()),
    sa.Column('wins', sa.Integer()),
    sa.Column('gaa', sa.Integer()),
    sa.Column('svp', sa.Integer()),
    sa.Column('gp', sa.Integer()),
    sa.Column('age', sa.Integer()),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'])
    )

    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('merch_id', sa.Integer()),
    sa.Column('memory_id', sa.Integer()),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id']),
    sa.ForeignKeyConstraint(['merch_id'], ['merchandise.id'])
    )

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer()),
    sa.Column('news_id', sa.Integer()),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id']),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id']),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'])
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE memories SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE news SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE merchandise SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE teams SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE players SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE images SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###qqqqqqqqq


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('memories')
    op.drop_table('news')
    op.drop_table('merchandise')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_table('images')
    op.drop_table('comments')
    # ### end Alembic commands ###
